"""
Script de seed: carga ejercicios de ejemplo en las 4 áreas.

Uso (parado en la carpeta backend/, con el venv activado):
    python seed_exercises.py

Es seguro correrlo más de una vez: si ya existen ejercicios, no duplica
(chequea por el texto del enunciado antes de insertar).
"""
from database import SessionLocal
import models

EXERCISES = [
    # ==================== ÁLGEBRA ====================
    {
        "area": "algebra",
        "topic": "ecuaciones lineales",
        "level": "terciario",
        "difficulty": "easy",
        "statement": "Resolvé: 2x + 3 = 11",
        "exercise_type": "numeric",
        "answer_data": {"value": 4.0, "tolerance": 0.01, "explanation": "2x = 8 → x = 4"},
    },
    {
        "area": "algebra",
        "topic": "ecuaciones cuadráticas",
        "level": "terciario",
        "difficulty": "medium",
        "statement": "¿Cuál es una de las soluciones de x^2 - 5x + 6 = 0?",
        "exercise_type": "numeric",
        "answer_data": {"value": 2.0, "tolerance": 0.01, "explanation": "(x-2)(x-3)=0 → x=2 o x=3"},
    },
    {
        "area": "algebra",
        "topic": "factorización",
        "level": "universitario",
        "difficulty": "medium",
        "statement": "Factorizá la expresión: x^2 - 5*x + 6",
        "exercise_type": "expression",
        "answer_data": {"value": "(x-2)*(x-3)", "explanation": "Buscamos dos números que sumen -5 y multipliquen 6: -2 y -3."},
    },
    {
        "area": "algebra",
        "topic": "conceptos básicos",
        "level": "terciario",
        "difficulty": "easy",
        "statement": "¿Cuál es el grado del polinomio 3x^4 - 2x + 1?",
        "exercise_type": "multiple_choice",
        "answer_data": {
            "correct_option": "b",
            "options": {"a": "2", "b": "4", "c": "3", "d": "1"},
            "explanation": "El grado es el mayor exponente de la variable: 4.",
        },
    },
    {
        "area": "algebra",
        "topic": "sistemas de ecuaciones",
        "level": "terciario",
        "difficulty": "medium",
        "statement": "Resolvé el sistema: x + y = 5, x - y = 1. ¿Cuánto vale x?",
        "exercise_type": "numeric",
        "answer_data": {"value": 3.0, "tolerance": 0.01, "explanation": "Sumando ambas ecuaciones: 2x = 6 → x = 3."},
    },
    {
        "area": "algebra",
        "topic": "sistemas de ecuaciones",
        "level": "terciario",
        "difficulty": "medium",
        "statement": "Resolvé el sistema: 2x + y = 7, x - y = 2. ¿Cuánto vale y?",
        "exercise_type": "numeric",
        "answer_data": {"value": 1.0, "tolerance": 0.01, "explanation": "De la segunda: x = y+2. Reemplazando en la primera: 2(y+2)+y=7 → y=1."},
    },
    {
        "area": "algebra",
        "topic": "simplificación",
        "level": "terciario",
        "difficulty": "easy",
        "statement": "Simplificá la expresión: (x^2 - 1)/(x - 1)",
        "exercise_type": "expression",
        "answer_data": {"value": "x+1", "explanation": "x²-1 se factoriza como (x-1)(x+1); se cancela (x-1)."},
    },
    {
        "area": "algebra",
        "topic": "simplificación",
        "level": "terciario",
        "difficulty": "easy",
        "statement": "Simplificá la expresión: 3*x + 2*x - 5",
        "exercise_type": "expression",
        "answer_data": {"value": "5*x - 5", "explanation": "Se agrupan los términos con x: 3x+2x=5x."},
    },
    {
        "area": "algebra",
        "topic": "factorización",
        "level": "terciario",
        "difficulty": "easy",
        "statement": "Factorizá: x^2 - 9",
        "exercise_type": "expression",
        "answer_data": {"value": "(x-3)*(x+3)", "explanation": "Diferencia de cuadrados: a²-b² = (a-b)(a+b)."},
    },
    {
        "area": "algebra",
        "topic": "factorización",
        "level": "terciario",
        "difficulty": "medium",
        "statement": "Factorizá: x^2 + 6*x + 9",
        "exercise_type": "expression",
        "answer_data": {"value": "(x+3)**2", "explanation": "Es un trinomio cuadrado perfecto: (x+3)²."},
    },
    {
        "area": "algebra",
        "topic": "expansión",
        "level": "terciario",
        "difficulty": "easy",
        "statement": "Expandí: (x+2)*(x+3)",
        "exercise_type": "expression",
        "answer_data": {"value": "x**2 + 5*x + 6", "explanation": "Propiedad distributiva: x²+3x+2x+6."},
    },
    {
        "area": "algebra",
        "topic": "expansión",
        "level": "terciario",
        "difficulty": "easy",
        "statement": "Expandí: (x-1)^2",
        "exercise_type": "expression",
        "answer_data": {"value": "x**2 - 2*x + 1", "explanation": "Cuadrado de un binomio: (a-b)² = a² - 2ab + b²."},
    },
    {
        "area": "algebra",
        "topic": "ecuaciones lineales",
        "level": "terciario",
        "difficulty": "easy",
        "statement": "Resolvé: 3*x - 7 = 2*x + 5",
        "exercise_type": "numeric",
        "answer_data": {"value": 12.0, "tolerance": 0.01, "explanation": "3x - 2x = 5 + 7 → x = 12."},
    },
    {
        "area": "algebra",
        "topic": "ecuaciones con valor absoluto",
        "level": "universitario",
        "difficulty": "medium",
        "statement": "¿Cuál es la solución negativa de |x| = 5?",
        "exercise_type": "numeric",
        "answer_data": {"value": -5.0, "tolerance": 0.01, "explanation": "|x|=5 tiene dos soluciones: x=5 y x=-5."},
    },

    # ==================== GEOMETRÍA ====================
    {
        "area": "geometry",
        "topic": "triángulos",
        "level": "terciario",
        "difficulty": "easy",
        "statement": "Un triángulo rectángulo tiene catetos de 3 y 4. ¿Cuánto mide la hipotenusa?",
        "exercise_type": "numeric",
        "answer_data": {"value": 5.0, "tolerance": 0.01, "explanation": "Teorema de Pitágoras: √(3²+4²) = 5"},
    },
    {
        "area": "geometry",
        "topic": "circunferencia",
        "level": "terciario",
        "difficulty": "easy",
        "statement": "¿Cuál es el área de un círculo de radio 2? (usá π ≈ 3.1416, redondeá a 2 decimales)",
        "exercise_type": "numeric",
        "answer_data": {"value": 12.57, "tolerance": 0.05, "explanation": "A = π*r² = π*4 ≈ 12.57"},
    },
    {
        "area": "geometry",
        "topic": "polígonos",
        "level": "universitario",
        "difficulty": "medium",
        "statement": "¿Cuántos grados mide cada ángulo interior de un hexágono regular?",
        "exercise_type": "numeric",
        "answer_data": {"value": 120.0, "tolerance": 0.01, "explanation": "((6-2)*180)/6 = 120°"},
    },
    {
        "area": "geometry",
        "topic": "cuadriláteros",
        "level": "terciario",
        "difficulty": "easy",
        "statement": "Un rectángulo tiene base 6 y altura 4. ¿Cuál es su área?",
        "exercise_type": "numeric",
        "answer_data": {"value": 24.0, "tolerance": 0.01, "explanation": "Área = base × altura = 6 × 4."},
    },
    {
        "area": "geometry",
        "topic": "cuadriláteros",
        "level": "terciario",
        "difficulty": "easy",
        "statement": "Un rectángulo tiene base 6 y altura 4. ¿Cuál es su perímetro?",
        "exercise_type": "numeric",
        "answer_data": {"value": 20.0, "tolerance": 0.01, "explanation": "Perímetro = 2×(base + altura) = 2×10."},
    },
    {
        "area": "geometry",
        "topic": "cuadriláteros",
        "level": "terciario",
        "difficulty": "easy",
        "statement": "Un cuadrado tiene lado 7. ¿Cuál es su área?",
        "exercise_type": "numeric",
        "answer_data": {"value": 49.0, "tolerance": 0.01, "explanation": "Área = lado² = 7²."},
    },
    {
        "area": "geometry",
        "topic": "triángulos",
        "level": "terciario",
        "difficulty": "easy",
        "statement": "Un triángulo tiene base 10 y altura 6. ¿Cuál es su área?",
        "exercise_type": "numeric",
        "answer_data": {"value": 30.0, "tolerance": 0.01, "explanation": "Área = (base × altura) / 2 = 60/2."},
    },
    {
        "area": "geometry",
        "topic": "triángulos",
        "level": "terciario",
        "difficulty": "easy",
        "statement": "¿Cuánto mide la hipotenusa de un triángulo rectángulo con catetos 6 y 8?",
        "exercise_type": "numeric",
        "answer_data": {"value": 10.0, "tolerance": 0.01, "explanation": "Pitágoras: √(6²+8²) = √100 = 10."},
    },
    {
        "area": "geometry",
        "topic": "triángulos",
        "level": "terciario",
        "difficulty": "medium",
        "statement": "¿Cuántos grados suman los ángulos interiores de cualquier triángulo?",
        "exercise_type": "numeric",
        "answer_data": {"value": 180.0, "tolerance": 0.01, "explanation": "Es una propiedad general de los triángulos en geometría plana."},
    },
    {
        "area": "geometry",
        "topic": "triángulos",
        "level": "universitario",
        "difficulty": "medium",
        "statement": "¿Cómo se llama un triángulo con los tres lados de distinta longitud?",
        "exercise_type": "multiple_choice",
        "answer_data": {
            "correct_option": "c",
            "options": {"a": "Equilátero", "b": "Isósceles", "c": "Escaleno", "d": "Regular"},
            "explanation": "Escaleno: los tres lados (y los tres ángulos) son distintos entre sí.",
        },
    },
    {
        "area": "geometry",
        "topic": "cuadriláteros",
        "level": "universitario",
        "difficulty": "medium",
        "statement": "¿Cuántos grados suman los ángulos interiores de cualquier cuadrilátero?",
        "exercise_type": "numeric",
        "answer_data": {"value": 360.0, "tolerance": 0.01, "explanation": "Un cuadrilátero se puede dividir en 2 triángulos: 2×180°."},
    },
    {
        "area": "geometry",
        "topic": "circunferencia",
        "level": "terciario",
        "difficulty": "medium",
        "statement": "¿Cuál es el perímetro (circunferencia) de un círculo de radio 5? (usá π ≈ 3.1416, redondeá a 2 decimales)",
        "exercise_type": "numeric",
        "answer_data": {"value": 31.42, "tolerance": 0.05, "explanation": "Perímetro = 2πr = 2×3.1416×5."},
    },

    # ==================== CÁLCULO — DERIVADAS ====================
    {
        "area": "calculus",
        "topic": "derivadas",
        "level": "universitario",
        "difficulty": "easy",
        "statement": "Derivá f(x) = x^3 respecto a x",
        "exercise_type": "expression",
        "answer_data": {"value": "3*x**2", "explanation": "Regla de la potencia: d/dx x^n = n*x^(n-1)"},
    },
    {
        "area": "calculus",
        "topic": "derivadas",
        "level": "universitario",
        "difficulty": "easy",
        "statement": "Si f(x) = 5*x, ¿cuánto vale f'(x) para cualquier valor de x?",
        "exercise_type": "numeric",
        "answer_data": {"value": 5.0, "tolerance": 0.01, "explanation": "La derivada de una función lineal a*x es la constante a."},
    },
    {
        "area": "calculus",
        "topic": "derivadas",
        "level": "universitario",
        "difficulty": "easy",
        "statement": "Derivá f(x) = x^2 + 3*x respecto a x",
        "exercise_type": "expression",
        "answer_data": {"value": "2*x + 3", "explanation": "Derivamos término a término: d/dx x² = 2x, d/dx 3x = 3."},
    },
    {
        "area": "calculus",
        "topic": "derivadas",
        "level": "universitario",
        "difficulty": "easy",
        "statement": "Derivá f(x) = sin(x) respecto a x",
        "exercise_type": "expression",
        "answer_data": {"value": "cos(x)", "explanation": "La derivada de sin(x) es cos(x)."},
    },
    {
        "area": "calculus",
        "topic": "derivadas",
        "level": "universitario",
        "difficulty": "medium",
        "statement": "Calculá f'(2) si f(x) = x^3 - 4*x",
        "exercise_type": "numeric",
        "answer_data": {"value": 8.0, "tolerance": 0.01, "explanation": "f'(x) = 3x² - 4. En x=2: 3(4) - 4 = 8."},
    },
    {
        "area": "calculus",
        "topic": "derivadas",
        "level": "universitario",
        "difficulty": "medium",
        "statement": "Derivá f(x) = x^2 * exp(x) respecto a x (regla del producto)",
        "exercise_type": "expression",
        "answer_data": {
            "value": "2*x*exp(x) + x**2*exp(x)",
            "explanation": "Regla del producto: (u*v)' = u'v + uv', con u=x², v=exp(x).",
        },
    },
    {
        "area": "calculus",
        "topic": "derivadas",
        "level": "universitario",
        "difficulty": "medium",
        "statement": "¿Cuál es la derivada de f(x) = log(x)? (log natural)",
        "exercise_type": "multiple_choice",
        "answer_data": {
            "correct_option": "a",
            "options": {"a": "1/x", "b": "x", "c": "log(x)", "d": "exp(x)"},
            "explanation": "La derivada de ln(x) es 1/x.",
        },
    },
    {
        "area": "calculus",
        "topic": "derivadas",
        "level": "universitario",
        "difficulty": "medium",
        "statement": "Derivá f(x) = (2*x+1)^3 respecto a x (regla de la cadena)",
        "exercise_type": "expression",
        "answer_data": {"value": "6*(2*x + 1)**2", "explanation": "Regla de la cadena: 3(2x+1)² × 2 = 6(2x+1)²."},
    },
    {
        "area": "calculus",
        "topic": "derivadas",
        "level": "universitario",
        "difficulty": "medium",
        "statement": "Derivá f(x) = exp(2*x) respecto a x",
        "exercise_type": "expression",
        "answer_data": {"value": "2*exp(2*x)", "explanation": "Regla de la cadena: la derivada de exp(u) es exp(u)×u', con u=2x."},
    },
    {
        "area": "calculus",
        "topic": "derivadas",
        "level": "universitario",
        "difficulty": "hard",
        "statement": "Derivá f(x) = sin(x)*cos(x) respecto a x",
        "exercise_type": "expression",
        "answer_data": {
            "value": "cos(x)**2 - sin(x)**2",
            "explanation": "Regla del producto, o equivalente a cos(2x) usando identidades trigonométricas.",
        },
    },
    {
        "area": "calculus",
        "topic": "derivadas",
        "level": "universitario",
        "difficulty": "hard",
        "statement": "¿En qué valor positivo de x la función f(x) = x^3 - 3*x tiene un punto crítico?",
        "exercise_type": "numeric",
        "answer_data": {"value": 1.0, "tolerance": 0.01, "explanation": "f'(x) = 3x² - 3 = 0 → x = ±1. El positivo es x=1."},
    },

    # ==================== CÁLCULO — LÍMITES ====================
    {
        "area": "calculus",
        "topic": "límites",
        "level": "universitario",
        "difficulty": "medium",
        "statement": "Calculá: límite de sin(x)/x cuando x tiende a 0",
        "exercise_type": "numeric",
        "answer_data": {"value": 1.0, "tolerance": 0.01, "explanation": "Es un límite notable: vale 1."},
    },
    {
        "area": "calculus",
        "topic": "límites",
        "level": "universitario",
        "difficulty": "easy",
        "statement": "Calculá: límite de (x^2-4)/(x-2) cuando x tiende a 2",
        "exercise_type": "numeric",
        "answer_data": {"value": 4.0, "tolerance": 0.01, "explanation": "(x²-4)/(x-2) = (x-2)(x+2)/(x-2) = x+2, que en x=2 vale 4."},
    },
    {
        "area": "calculus",
        "topic": "límites",
        "level": "universitario",
        "difficulty": "easy",
        "statement": "Calculá: límite de 1/x cuando x tiende a infinito",
        "exercise_type": "numeric",
        "answer_data": {"value": 0.0, "tolerance": 0.01, "explanation": "A medida que x crece sin límite, 1/x se acerca a 0."},
    },

    # ==================== CÁLCULO — INTEGRALES ====================
    {
        "area": "calculus",
        "topic": "integrales",
        "level": "universitario",
        "difficulty": "easy",
        "statement": "Calculá la integral indefinida de 2*x respecto a x (sin agregar la constante C)",
        "exercise_type": "expression",
        "answer_data": {"value": "x**2", "explanation": "∫2x dx = x² + C"},
    },
    {
        "area": "calculus",
        "topic": "integrales",
        "level": "universitario",
        "difficulty": "easy",
        "statement": "Calculá la integral indefinida de 3*x^2 respecto a x (sin la constante C)",
        "exercise_type": "expression",
        "answer_data": {"value": "x**3", "explanation": "Regla inversa de la potencia: ∫x^n dx = x^(n+1)/(n+1)."},
    },
    {
        "area": "calculus",
        "topic": "integrales",
        "level": "universitario",
        "difficulty": "easy",
        "statement": "Calculá la integral indefinida de cos(x) respecto a x (sin la constante C)",
        "exercise_type": "expression",
        "answer_data": {"value": "sin(x)", "explanation": "∫cos(x) dx = sin(x) + C"},
    },
    {
        "area": "calculus",
        "topic": "integrales",
        "level": "universitario",
        "difficulty": "medium",
        "statement": "Calculá la integral definida de x entre 0 y 4",
        "exercise_type": "numeric",
        "answer_data": {"value": 8.0, "tolerance": 0.01, "explanation": "∫x dx = x²/2. Evaluado entre 0 y 4: 16/2 - 0 = 8."},
    },
    {
        "area": "calculus",
        "topic": "integrales",
        "level": "universitario",
        "difficulty": "medium",
        "statement": "Calculá la integral definida de 2*x entre 1 y 3",
        "exercise_type": "numeric",
        "answer_data": {"value": 8.0, "tolerance": 0.01, "explanation": "∫2x dx = x². Evaluado entre 1 y 3: 9 - 1 = 8."},
    },
    {
        "area": "calculus",
        "topic": "integrales",
        "level": "universitario",
        "difficulty": "medium",
        "statement": "Calculá la integral indefinida de 1/x respecto a x (sin la constante C)",
        "exercise_type": "expression",
        "answer_data": {"value": "log(x)", "explanation": "∫(1/x) dx = ln(x) + C (SymPy escribe el logaritmo natural como log)."},
    },
    {
        "area": "calculus",
        "topic": "integrales",
        "level": "universitario",
        "difficulty": "medium",
        "statement": "¿Cuál es la integral indefinida de sin(x)? (sin la constante C)",
        "exercise_type": "multiple_choice",
        "answer_data": {
            "correct_option": "a",
            "options": {"a": "-cos(x)", "b": "cos(x)", "c": "-sin(x)", "d": "sin(x)"},
            "explanation": "∫sin(x) dx = -cos(x) + C",
        },
    },
    {
        "area": "calculus",
        "topic": "integrales",
        "level": "universitario",
        "difficulty": "medium",
        "statement": "Calculá la integral definida de x^2 entre 0 y 2",
        "exercise_type": "numeric",
        "answer_data": {"value": 2.6667, "tolerance": 0.01, "explanation": "∫x² dx = x³/3. Evaluado entre 0 y 2: 8/3 ≈ 2.6667."},
    },
    {
        "area": "calculus",
        "topic": "integrales",
        "level": "universitario",
        "difficulty": "hard",
        "statement": "Calculá el área bajo la curva f(x) = x^2 entre x=0 y x=3",
        "exercise_type": "numeric",
        "answer_data": {"value": 9.0, "tolerance": 0.01, "explanation": "∫x² dx = x³/3. Evaluado entre 0 y 3: 27/3 - 0 = 9."},
    },
    {
        "area": "calculus",
        "topic": "integrales",
        "level": "universitario",
        "difficulty": "hard",
        "statement": "Calculá la integral indefinida de 2*exp(x) respecto a x (sin la constante C)",
        "exercise_type": "expression",
        "answer_data": {"value": "2*exp(x)", "explanation": "∫exp(x) dx = exp(x) + C, multiplicado por la constante 2."},
    },

    # ==================== ESTADÍSTICA Y PROBABILIDAD ====================
    {
        "area": "statistics",
        "topic": "estadística descriptiva",
        "level": "terciario",
        "difficulty": "easy",
        "statement": "¿Cuál es la media de los datos: 2, 4, 6, 8?",
        "exercise_type": "numeric",
        "answer_data": {"value": 5.0, "tolerance": 0.01, "explanation": "(2+4+6+8)/4 = 5"},
    },
    {
        "area": "statistics",
        "topic": "probabilidad",
        "level": "terciario",
        "difficulty": "easy",
        "statement": "Al tirar un dado justo de 6 caras, ¿cuál es la probabilidad de sacar un número par? (como decimal)",
        "exercise_type": "numeric",
        "answer_data": {"value": 0.5, "tolerance": 0.01, "explanation": "3 de 6 caras son pares: 3/6 = 0.5"},
    },
    {
        "area": "statistics",
        "topic": "conceptos básicos",
        "level": "universitario",
        "difficulty": "medium",
        "statement": "¿Cuál de estas medidas es más sensible a valores extremos (outliers)?",
        "exercise_type": "multiple_choice",
        "answer_data": {
            "correct_option": "a",
            "options": {"a": "Media", "b": "Mediana", "c": "Moda", "d": "Ninguna"},
            "explanation": "La media se ve afectada por valores extremos; la mediana y la moda son más robustas.",
        },
    },
    {
        "area": "statistics",
        "topic": "estadística descriptiva",
        "level": "terciario",
        "difficulty": "easy",
        "statement": "¿Cuál es la mediana de los datos: 3, 7, 9, 15, 20?",
        "exercise_type": "numeric",
        "answer_data": {"value": 9.0, "tolerance": 0.01, "explanation": "Con los datos ya ordenados, la mediana es el valor central: 9."},
    },
    {
        "area": "statistics",
        "topic": "estadística descriptiva",
        "level": "terciario",
        "difficulty": "easy",
        "statement": "¿Cuál es la moda de los datos: 2, 2, 3, 5, 8?",
        "exercise_type": "numeric",
        "answer_data": {"value": 2.0, "tolerance": 0.01, "explanation": "La moda es el valor que más se repite: 2 aparece dos veces."},
    },
    {
        "area": "statistics",
        "topic": "combinatoria",
        "level": "terciario",
        "difficulty": "easy",
        "statement": "Se tira una moneda 3 veces seguidas. ¿Cuántas secuencias distintas de cara/ceca son posibles en total?",
        "exercise_type": "numeric",
        "answer_data": {"value": 8.0, "tolerance": 0.01, "explanation": "2 resultados posibles por tirada, elevado a 3 tiradas: 2³ = 8."},
    },
    {
        "area": "statistics",
        "topic": "combinatoria",
        "level": "universitario",
        "difficulty": "medium",
        "statement": "De un mazo de 52 cartas, ¿cuántas manos distintas de 5 cartas se pueden formar? (es la misma cuenta que usa el laboratorio de Póker)",
        "exercise_type": "numeric",
        "answer_data": {"value": 2598960.0, "tolerance": 1, "explanation": "C(52,5) = 52!/(5!·47!) = 2.598.960."},
    },
    {
        "area": "statistics",
        "topic": "combinatoria",
        "level": "universitario",
        "difficulty": "medium",
        "statement": "Si elegís 6 números de un bolillero del 1 al 45, ¿cuántas combinaciones distintas de 6 números existen? (usá el laboratorio de Lotería para verificarlo)",
        "exercise_type": "numeric",
        "answer_data": {"value": 8145060.0, "tolerance": 1, "explanation": "C(45,6) = 45!/(6!·39!) = 8.145.060."},
    },
    {
        "area": "statistics",
        "topic": "probabilidad",
        "level": "universitario",
        "difficulty": "medium",
        "statement": "Según la paradoja del cumpleaños, ¿a partir de cuántas personas en una sala la probabilidad de que dos compartan cumpleaños supera el 50%?",
        "exercise_type": "numeric",
        "answer_data": {"value": 23.0, "tolerance": 0.01, "explanation": "Es el número clásico: con 23 personas la probabilidad ya supera el 50%. Podés verificarlo en el laboratorio."},
    },
    {
        "area": "statistics",
        "topic": "probabilidad",
        "level": "universitario",
        "difficulty": "medium",
        "statement": "En el problema de Monty Hall clásico (3 puertas), ¿cuál es la probabilidad de ganar si SIEMPRE cambiás de puerta? (como decimal, ej: 0.5)",
        "exercise_type": "numeric",
        "answer_data": {"value": 0.6667, "tolerance": 0.01, "explanation": "P(ganar cambiando) = 2/3 ≈ 0.6667. Comparalo con el laboratorio de Monty Hall."},
    },
    {
        "area": "statistics",
        "topic": "probabilidad",
        "level": "universitario",
        "difficulty": "medium",
        "statement": "En la ruleta europea (37 casilleros), ¿cuál es aproximadamente la ventaja de la banca en cualquier apuesta simple?",
        "exercise_type": "multiple_choice",
        "answer_data": {
            "correct_option": "a",
            "options": {"a": "2.7%", "b": "5.26%", "c": "10%", "d": "0%"},
            "explanation": "1/37 ≈ 2.70%, la misma para cualquier apuesta simple en la ruleta europea.",
        },
    },
]


def run_seed():
    db = SessionLocal()
    try:
        inserted = 0
        skipped = 0
        for ex in EXERCISES:
            exists = (
                db.query(models.Exercise)
                .filter(models.Exercise.statement == ex["statement"])
                .first()
            )
            if exists:
                skipped += 1
                continue

            db.add(models.Exercise(**ex))
            inserted += 1

        db.commit()
        print(f"Listo. Insertados: {inserted}, ya existían (saltados): {skipped}")
    finally:
        db.close()


if __name__ == "__main__":
    run_seed()